codespider/urls.py
from django.contrib import admin
from django.urls import path, re_path, register_converter, include
from main.views import *

# import debug_toolbar

urlpatterns = [
    # path('debug', include(debug_toolbar.urls)),

    # main pages
    # path('asd', tmp_date, name='asd'),
    # re_path('asd/(?P<year>(\d{4}))/(?P<month>(\d{2}))/(?P<day>(\d{2}))', tmp_date),
    # path('asd/<yyyy:year>/<mm:month>', tmp_date),
    # re_path(r'^fish$', regex, name='fish'),
    # re_path(r'^fish/(?P<test>(main)|(annex))$', regex),
    
    path('home'             , home          , name='home'),
    path(''             , home          , name='home'),
    re_path('summary/monthly/(?P<year>(\d{4}))/(?P<month>(\d{2}))', get_summary_monthly),
    re_path('rooms/(?P<building>([a-zA-Z]+))', rooms),
    # re_path('rooms/(?P<building>([a-zA-Z]+))/(?P<year>(\d{4}))/(?P<month>(\d{2}))/(?P<day>(\d{2}))', rooms),
    # re_path('rooms/(?P<building>([a-zA-Z]+))', rooms),
    path('rooms/main'        , rooms     , name='rooms/main'),
    path('rooms/annex'        , rooms     , name='rooms/annex'),
    path('patients'         , patients  , name='patients'),
    # path('summary/daily'      , summary_daily   , name='summary/daily'),
    re_path('summary/daily/(?P<year>(\d{4}))/(?P<month>(\d{2}))/(?P<day>(\d{2}))', summary_daily),
    path('summary/daily'      , summary_daily   , name='summary/daily'),
    path('summary/monthly'  , summary_monthly   , name='summary/monthly'),
    path('inquiry/filter'      , inquiry_filter   , name='inquiry/filter'),
    path('inquiry/sort'      , inquiry_sort   , name='inquiry/sort'),
    path('login'              , login   , name='login'),

    # temporary
    path('tmp/create-patient', tmp_create_patient, name="forms/create-patient"),
    path('tmp/assign-room', tmp_assign_room, name="forms/assign-room"),
    path('tmp/rand', rand_patient, name="rand"),

    # requires input
    path('tmp/action/create-patient', tmp_create_patient, name='action/create-patient'),
    path('action/assign-room', assign_room, name='action/assign-room'),
    path('action/checkout', checkout, name='action/checkout'),
    path('action/transfer-room', transfer_room, name='action/transfer-room'),

    path('actions/get-filtered-patient-names', get_filtered_patient_names, name='actions/get-filtered-patient-names'),
    path('actions/get-filtered-relationships', get_filtered_relationships, name='actions/get-filtered-relationships'),
    path('actions/save-day', save_day, name='actions/save-day'),
    path('actions/logout', logout_view, name='actions/logout'),

     
    path('dev', show_urls, name='dev/show-urls'),

    # admin
    path('admin', admin.site.urls, name='admin'),
]

main/models/building.py
from django.db import models

class BuildingManager(models.Manager):
    def get_list(self):
        return [[b.pk, b.name] for b in super().get_queryset()]
	
class Building(models.Model):
    objects = BuildingManager()
    name = models.CharField(max_length=20)
    def __str__(self):
        return self.name

main/models/diagnosis.py
from django.db import models

class DiagnosisManager(models.Manager):
    def get_diagnosis_list(self):
        diagnosis_qset = super().get_queryset()
        diagnoses = list(diagnosis_qset)
        diagnoses_new = []
        for i in range (len(diagnosis_qset)):
            diagnoses_new.append([
                diagnosis_qset[i].id, 
                ""+diagnosis_qset[i].full_name
            ])
        return diagnoses_new

class Diagnosis(models.Model):
    objects = DiagnosisManager()
    full_name = models.CharField(max_length=60)
    def __str__(self):
        return self.full_name
    class Meta:
         verbose_name_plural = "diagnoses"

main/models/extension.py
from django.db import models


class Extension(models.Model):
    visit = models.ForeignKey("Visit", on_delete=models.CASCADE)
    old_assigned_end_date = models.DateTimeField()

    def __str__(self):
        return self.old_assigned_end_date

main/models/patient.py
from django.db import models

from .diagnosis import Diagnosis
from main.enums import Enums
from .visit import Visit
from .occupancy import Occupancy

def simplify_patient_name(patient):
    return {
        'pk': patient.pk,
        'first_name': patient.first_name,
        'last_name': patient.last_name,
        'middle_initial': patient.middle_initial,
    }
    
def simplify_patient_extended(patient):
    return {
        'pk': patient.pk,
        'first_name': patient.first_name,
        'last_name': patient.last_name,
        'middle_initial': patient.middle_initial,
    }

class PatientsManager(models.Manager):
    def get_list_names(self):
        return map(simplify_patient_name, super().get_queryset())
    
    def get_by_name(self, last, first, mid):
        # super().get_queryset()  <---- get all patients
        return super().get_queryset().filter(last_name=last, first_name=first, middle_initial=mid)

    def get_filtered_names(self, term):
        # filters = {}
        # if first:
        #     filters['first_name__icontains'] = first
        # if mid:
        #     filters['middle_initial__iexact'] = mid
        # if last:
        #     filters['last_name__icontains'] = last
        query = super().get_queryset().filter(
            models.Q(first_name__icontains=term) |
            models.Q(middle_initial__iexact=term) |
            models.Q(last_name__icontains=term)
            )


        return list(map(simplify_patient_name, query))
        
    def get_diagnosis_region(self, start, end, diag, reg):
        
        # if diag != None:
            # regs = []
            # visits = Visit.objects.filter(diagnosis=diag)
            # for reg in Enums.REGIONS[1:]:
                # print 
                # regs.append([reg[1], pats.filter(region=reg[0]).count()])
            # return regs
            
        # if reg != None:
            # diags = []
            # pats = super().get_queryset().filter(region=reg)
            # for diag in Diagnosis.objects.all():
                # diags.append([diag.full_name, pats.filter(diagnosis=diag).count()])
            # return diags
            
        return []
        
    def get_history(self):
        pats = []
        for pat in super().get_queryset().all():
            
            code = pat.city
            reg = [x[1] for x in Enums.REGIONS if x[0] == code[0:2]][0]
            if reg.startswith('r'):
                reg = reg.split('-')[1].strip()
            else:
                reg = reg.split('-')[0].strip()
            prov = [x[1] for x in Enums.PROVINCES if x[0] == code[0:4]][0]
            city = [x[1] for x in Enums.CITIES if x[0] == code[0:6]][0]
        
            pats.append({
                'first_name': pat.first_name,
                'last_name': pat.last_name,
                'middle_initial': pat.middle_initial,
                'age': pat.age,
                'sex': pat.sex,
                'region': reg,
                'diagnosis': pat.diagnosis.full_name,
                'province': prov,
                'city': city,
                'total_days': Visit.objects.filter(patient=pat).count(),
                'frequency': Occupancy.objects.filter(visit__patient=pat).count(),
                'dates_of_stay': [
                    {'from': x.start_date.strftime('%Y-%m-%d'), 
                    'to': x.assigned_end_date.strftime('%Y-%m-%d')}
                    for x in Visit.objects.filter(patient=pat)],
            
            })
        return pats
                

class Patient(models.Model):
    objects = PatientsManager()
    first_name = models.TextField()
    last_name = models.TextField()
    middle_initial = models.CharField(max_length=1)
    age = models.SmallIntegerField()
    sex = models.CharField(max_length=1)
    diagnosis = models.ForeignKey("Diagnosis",on_delete=models.CASCADE,null=True,blank=True)
    region = models.CharField(max_length=6)
    province = models.CharField(max_length=6)
    city = models.CharField(max_length=6, null=True, blank=True)
    def __str__(self):
        return self.last_name

main/models/room.py
from django.db import models

class RoomManager(models.Manager):
    def get_list(self):
        return [
            [r.pk, r.building.pk, r.display_number]
            for r in super().get_queryset()
        ]

class Room(models.Model):
    objects = RoomManager()
    building = models.ForeignKey("Building", on_delete=models.CASCADE)
    display_number = models.PositiveSmallIntegerField()
    def __str__(self):
        return f'{self.building.name} - {self.display_number}'

main/models/saved_date.py
from django.db import models


class Saved_Date(models.Model):
    saved = models.NullBooleanField()
    last_modified = models.DateTimeField()

main/models/visit.py
from django.db import models

from main.enums import Enums
from .diagnosis import Diagnosis
# from .occupancy import Occupancy

class VisitManager(models.Manager):
    def get_ongoing_visit_by_patient_name(last, first, middle):
        pass
        
        
    
        
class Visit(models.Model):
    objects = VisitManager()
    patient = models.ForeignKey("Patient", on_delete=models.CASCADE)
    start_date = models.DateTimeField()
    assigned_end_date = models.DateTimeField()
    actual_end_date = models.DateTimeField(null=True,blank=True)
    is_ongoing = models.NullBooleanField()
    def __str__(self):
        return self.patient.last_name
        
    # def overlaps_date(self, start, end):
        # v = Visit.objects.filter(pk=self.pk, start_date__lte=)

main/models/watcher.py
from django.db import models

class WatcherManager(models.Manager):
    def get_relationship_list(self):
        return [[rel.pk, rel.relationship] for rel in super().get_queryset()]
        
    def get_filtered_relationships(self, term):
        return [
            {'pk': rel.pk, 'relationship': rel.relationship}
            for rel in super().get_queryset().filter(relationship__icontains=term)
        ]

class Watcher(models.Model):
    objects = WatcherManager()
    relationship = models.CharField(max_length=15)
    def __str__(self):
        return self.relationship

main/forms.py
from django import forms
from django.forms import ModelForm
from .models import Patient
from .enums import Enums
from .helpers import get_diagnosis_list
from .models import Diagnosis
from .models.watcher import Watcher

class UserForm(ModelForm):
	# Temporary unless no model for form
    username = forms.CharField (
        label = 'Username',
        widget = forms.TextInput ( attrs = {
            'class' : 'input',
            'placeholder' : 'Username'
        })
    )
    
    password = forms.CharField (
        widget = forms.PasswordInput ( attrs = {
            'class' : 'input',
            'placeholder' : 'Password'
        })
    )

class PatientForm(ModelForm):
    class Meta:
        model = Patient
        fields = ['last_name', 'first_name', 'middle_initial', 'age', 'sex', 'diagnosis', 'region', 'province', 'city']
        widgets = {
            'last_name': forms.TextInput ( attrs = {
                'class' : 'input',
                'placeholder' : 'Last Name'
            }),
			
			'first_name': forms.TextInput ( attrs = {
                'class' : 'input',
                'placeholder' : 'First Name'
            }),
			
			'middle_initial': forms.TextInput ( attrs = {
                'class' : 'input',
                'placeholder' : 'Middle Initial'
            }),
			
			'age': forms.NumberInput ( attrs = {
                'class' : 'form-control, input',
			    'placeholder' : 'Age',
				'min': 0,
				'max': 100
            }),
			
			'sex': forms.Select (
			    attrs = {
				    'class' : 'form-control, input'
			    },
                choices = Enums.SEX
            ),

            'diagnosis': forms.Select (
			    attrs = {
				    'class' : 'form-control, input'
			    },
                choices = [
				]
            ),
			
			'region': forms.Select (
			    attrs = {
				    'class' : 'form-control, input',
			    },
                choices = Enums.REGIONS,
            ),
			
			'province': forms.Select (
			    attrs = {
				    'class' : 'form-control, input'
			    },
                choices = Enums.PROVINCES
            ),
			
			'city': forms.Select (
			    attrs = {
				    'class' : 'form-control, input'
			    },
                choices = Enums.CITIES
            )
		}
	
class RoomForm(ModelForm):
    class Meta:
        model = Patient
        fields = ['last_name', 'first_name', 'middle_initial']
        widgets = {
            'last_name': forms.TextInput ( attrs = {
                'class' : 'input',
                'placeholder' : 'Last Name'
            }),
			
			'first_name': forms.TextInput ( attrs = {
                'class' : 'input',
                'placeholder' : 'First Name'
            }),
			
			'middle_initial': forms.TextInput ( attrs = {
                'class' : 'input',
                'placeholder' : 'Middle Initial'
            })
		}
		
    building_transfer = forms.CharField (
		widget = forms.Select (
			attrs = {
				'class' : 'form-control, input'
			},
			choices = [
			]
		)
	)
		
    room_num = forms.IntegerField (
		widget = forms.Select (
			attrs = {
				'class' : 'form-control, input'
			},
			choices = [
			]
		)
	)
	
    room_num_transfer = forms.IntegerField (
		widget = forms.Select (
			attrs = {
				'class' : 'form-control, input'
			},
			choices = [
			]
		)
	)

    relationship = forms.MultipleChoiceField (
		widget = forms.CheckboxSelectMultiple,
		choices = [
		]
    )
	
    date_from = forms.DateField(
        widget = forms.DateInput (
			format = '%m/%d/%Y',
			attrs = {
				'type': 'date',
				'class': 'form-control'
			})
		)
    
    date_to = forms.DateField(
        widget = forms.DateInput (
			format = '%m/%d/%Y',
			attrs = {
				'type': 'date',
				'class': 'form-control'
			})
		)
	
class FilterForm(ModelForm):		
    date_from = forms.DateField (
        widget = forms.DateInput (
			format = '%m/%d/%Y',
			attrs = {
				'type': 'date',
				'class': 'form-control'
			})
		)
    
    date_to = forms.DateField(
        widget = forms.DateInput (
			format = '%m/%d/%Y',
			attrs = {
				'type': 'date',
				'class': 'form-control'
			})
		)
	
    class Meta:
        model = Patient
        fields = ['diagnosis', 'region', 'province', 'city']
        widgets = {
            'diagnosis': forms.Select (
			    attrs = {
				    'class' : 'form-control, input'
			    },
                choices = [],
            ),
			
			'region': forms.Select (
			    attrs = {
				    'class' : 'form-control, input',
			    },
                choices = Enums.REGIONS,
            ),
			
			'province': forms.Select (
			    attrs = {
				    'class' : 'form-control, input'
			    },
                choices = Enums.PROVINCES
            ),
			
			'city': forms.Select (
			    attrs = {
				    'class' : 'form-control, input'
			    },
                choices = Enums.CITIES
            )
		}
		
class SummaryForm(ModelForm):
	class Meta:
		# TEMPORARY
		model = Patient
		fields = ['city']
		
	DateChosen = forms.DateField (
        widget = forms.DateInput (
			format = '%m/d%/%Y',
			attrs = {
				'type': 'date',
				'class': 'form-control'
			})
		)

main/templates/main/inquiry-filter.html
{% extends 'main/base.html' %}

{% block title %}Inquiry{% endblock title %}

{% load staticfiles %}
        
{% block page_titleicon %}
    <link rel="icon" type="image/png" href="{% static 'images/icons/inquiry_titleicon.png' %}">
{% endblock page_titleicon %}

{% block page_stylesheet %}
	<link rel="stylesheet" href="{% static 'css/inquiry.css' %}">
{% endblock page_stylesheet %}

{% block nav_bar %}
    <li class="nav-item"><a class="nav-link" href="{% url 'home' %}">Home</a></li>
                    
	<li class="nav-item dropdown">
		<a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown">Rooms</a>
		<div class="dropdown-menu dropdown-menu-right">
			<a class="nav-link" href="{% url 'rooms/main' %}">Main</a>
			<a class="nav-link" href="{% url 'rooms/annex' %}">Annex</a>
		</div>
	</li>
	
	<li class="nav-item"><a class="nav-link" href="{% url 'patients' %}">Patients</a></li>
	
	<li class="nav-item dropdown">
		<a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown">Summary</a>
		<div class="dropdown-menu dropdown-menu-right">
			<a class="nav-link" href="{% url 'summary/monthly' %}">Monthly</a>
			<a class="nav-link" href="{% url 'summary/daily' %}">Daily</a>
		</div>
	</li>
	
	<li class="nav-item dropdown">
		<a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown">Inquiry</a>
		<div class="dropdown-menu dropdown-menu-right">
			<a class="nav-link active" href="{% url 'inquiry/filter' %}">Filter</a>
			<a class="nav-link" href="{% url 'inquiry/sort' %}">Sort</a>
		</div>
	</li>
{% endblock nav_bar %}

{% block page_body %}
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-6">
			<div class="filter-container">
				<div class="filter-wrap">
					<div class="filter-content">
						<div class="filter-header filter-title">
							Filter
						</div>
						<form method="get" action="">
							<div class="filter-body">
								<div class="row">
									Date of Stay
								</div>
								<div class="row">
									<div class="col-lg-6">
										From
										{{ form.date_from }}
									</div>
									<div class="col-lg-6">
										To
										{{ form.date_to }}
									</div>
								</div>
								<div class="row">
									<div class="col-lg-12">
										{{ form.diagnosis }}
									</div>
								</div>
								<div class="row">
									<div class="col-lg-4">
										{{ form.region }}
									</div>
									<div class="col-lg-4">
										{{ form.province }}
									</div>
									<div class="col-lg-4">
										{{ form.city }}
									</div>
								</div>
							</div>
							<div class="filter-footer">
								<button type="submit" class="btn btn-success">
									<span>
										Search
										<i class="fa fa-search" aria-hidden="true"></i>
									</span>
								</button>
								<button type="button" class="btn btn-danger" data-dismiss="modal">
									<span>
										Clear
										<i class="fa fa-undo" aria-hidden="true"></i>
									</span>
								</button>
							</div>
						</form> 
					</div>
				</div>
			</div>
		</div>
		<div class="col-lg-6">
			<div class="results-container">
				<div class="results-wrap text-center">
					<div class="row">
						<div class="col-lg-12">
							Date:
							{{ date_from }} - {{ date_to }}
						</div>
					</div>
					<div class="row">
						<div class="col-lg-12">
							Diagnosis:
							{{ diagnosis }}
						</div>
					</div>
					<div class="row">
						<div class="col-lg-4">
							Region:
							{{ region }}
						</div>
						<div class="col-lg-4">
							Province:
							{{ province }}
						</div>
						<div class="col-lg-4">
							City:
							{{ city }}
						</div>
					</div>
					<table class="table">
						<thead>
							<tr class="table-head">
								<th class="f-col-1"></th>
								<th class="f-col-2">Both Bldgs</th>
								<th class="f-col-3">Main</th>
								<th class="f-col-4">Annex</th>
							</tr>
						</thead>

						<tbody">
							<tr>
								<td class="f-col-1">Patients</td>
								<td class="f-col-2">{{both.patients}}</td>
								<td class="f-col-3">{{main.patients}}</td>
								<td class="f-col-4">{{annex.patients}}</td>
							</tr>
							<tr>
								<td class="f-col-1">Boys</td>
								<td class="f-col-2">{{both.boys}}</td>
								<td class="f-col-3">{{main.boys}}</td>
								<td class="f-col-4">{{annex.boys}}</td>
							</tr>
							<tr>
								<td class="f-col-1">Girls</td>
								<td class="f-col-2">{{both.girls}}</td>
								<td class="f-col-3">{{main.girls}}</td>
								<td class="f-col-4">{{annex.girls}}</td>
							</tr>
							<tr>
								<td class="f-col-1">Watchers</td>
								<td class="f-col-2">{{both.watchers}}</td>
								<td class="f-col-3">{{main.watchers}}</td>
								<td class="f-col-4">{{annex.watchers}}</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>

<script>
$(document).ready(function() {

    $('#id_date_from, #id_date_to, #id_diagnosis, #id_province, #id_region, #id_city').removeAttr('required');

	let reg = $('select[name=region]');
	let prov = $('select[name=province]');
	let city = $('select[name=city]');

    let provinces = prov.children('option').detach();
    let cities = city.children('option').detach();

    function resetProv(){
        prov.children('option').detach();
        prov.append(provinces[0]);
        prov.val('');
        resetCity();
    }
    function resetCity(){
        city.children('option').detach();
        city.append(cities[0]);
        city.val('');
    }

    function doFilter(options, select, filter) {
        if (filter === '') return;
        options.filter((index, element) => {
            let val = $(element).val();
            return val.startsWith(filter) || val === '';
        }).appendTo(select);
        select.val('');
    }

	reg.change(function() {
		let filter = $(this).val();
        resetProv();
        doFilter(provinces, prov, filter);
	});
    prov.change(function() {
		let filter = $(this).val();
        resetCity();
        doFilter(cities, city, filter);
	});

    resetProv();
	
	// var diagnosis = {{diagnosis}};
	// console.log(diagnosis);
	// let dropdown = document.getElementById('id_diagnosis');
	// dropdown.innerHTML = ''
	// // console.log()
	
	// diagnosis.forEach(arrayopt);
	// function arrayopt(diagnosis){
	// 	let option = document.createElement('option'); // create option element
	// 	option.value = diagnosis[0]; // assign id/value
	// 	option.innerText = diagnosis[1]; // assign text
	// 	dropdown.appendChild(option); // add option to dropdown
	// }
});
</script>
{% endblock page_body %}

main/templates/main/inquiry-sort.html
{% extends 'main/base.html' %}

{% block title %}Inquiry{% endblock title %}

{% load staticfiles %}
    
        
{% block page_titleicon %}
    <link rel="icon" type="image/png" href="{% static 'images/icons/inquiry_titleicon.png' %}">
{% endblock page_titleicon %}

{% block page_stylesheet %}
	<link rel="stylesheet" href="{% static 'css/inquiry.css' %}">
{% endblock page_stylesheet %}

{% block nav_bar %}
    <li class="nav-item"><a class="nav-link" href="{% url 'home' %}">Home</a></li>
                    
	<li class="nav-item dropdown">
		<a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown">Rooms</a>
		<div class="dropdown-menu dropdown-menu-right">
			<a class="nav-link" href="{% url 'rooms/main' %}">Main</a>
			<a class="nav-link" href="{% url 'rooms/annex' %}">Annex</a>
		</div>
	</li>
	
	<li class="nav-item"><a class="nav-link" href="{% url 'patients' %}">Patients</a></li>
	
	<li class="nav-item dropdown">
		<a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown">Summary</a>
		<div class="dropdown-menu dropdown-menu-right">
			<a class="nav-link" href="{% url 'summary/monthly' %}">Monthly</a>
			<a class="nav-link" href="{% url 'summary/daily' %}">Daily</a>
		</div>
	</li>
	
	<li class="nav-item dropdown">
		<a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown">Inquiry</a>
		<div class="dropdown-menu dropdown-menu-right">
			<a class="nav-link" href="{% url 'inquiry/filter' %}">Filter</a>
			<a class="nav-link active" href="{% url 'inquiry/sort' %}">Sort</a>
		</div>
	</li>
{% endblock nav_bar %}

{% block page_body %}
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-6">
			<div class="filter-container">
				<div class="filter-wrap">
					<div class="filter-content">
						<div class="filter-header filter-title">
							Sort
						</div>
						<form method="get" action="">
							<div class="filter-body">
								<div class="row">
									Date of Stay
								</div>
								<div class="row">
									<div class="col-lg-6">
										From
										{{ form.date_from }}
									</div>
									<div class="col-lg-6">
										To
										{{ form.date_to }}
									</div>
								</div>
								<div class="row">
									<div class="col-lg-12 mt-3">
										{{ form.diagnosis }}
									</div>
								</div>
								<div class="row">
									<div class="col-lg-12">
										{{ form.region }}
									</div>
								</div>
							</div>
							<div class="filter-footer">
								<button type="submit" class="btn btn-success">
									<span>
										Sort
										<i class="fa fa-sort" aria-hidden="true"></i>
									</span>
								</button>
								<button type="button" class="btn btn-danger" data-dismiss="modal">
									<span>
										Clear
										<i class="fa fa-undo" aria-hidden="true"></i>
									</span>
								</button>
							</div>
						</form> 
					</div>
				</div>
			</div>
		</div>
		<div class="col-lg-6">
			<div class="results-container">
				<div class="results-wrap text-center">
					<div class="row">
						<div class="col-lg-12">
							Date:
							{{ date_from }} - {{ date_to }}
						</div>
					</div>
					<div class="row">
						<div class="col-lg-12">
							Diagnosis:
							{{ diagnosis }}
						</div>
					</div>
					<div class="row">
						<div class="col-lg-12">
							Region:
							{{ region }}
						</div>	
					</div>
				</div>
				<table class="table text-center">
					<thead>
						<tr class="table-head">
							<th class="s-col-1"></th>
							<th class="s-col-2">Number of Patients</th>
						</tr>
                        <tr class="tabel-head">
                            <td class="s-col-1"></td>
                            <td class="s-col-2">{{ count.patients }}</td>
                        </tr>
					</thead>

					<tbody>
						{% for d in diags %}
						<tr>
							<td class="s-col-1">{{ d.0 }}</td>
							<td class="s-col-2">{{ d.1 }}</td>
						</tr>
						{% endfor %}
					</tbody>
                </table>
			</div>
		</div>
	</div>
</div>

<script>
$(document).ready(function() {
    console.log('asdasdasd');
    $('#id_diagnosis, #id_region').removeAttr('required');

});
</script>

{% endblock page_body %}

main/templates/main/login.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Login</title>
        {% load staticfiles %}
        
        <link rel="icon" type="image/png" href="{% static 'images/icons/login_titleicon.png' %}">
        
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
		<link rel="stylesheet" href="{% static 'css/login.css' %}">
    </head>
    
    <body>
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-12 login-container" style="background-image: url({% static 'images/login_bg01.jpg' %});">
					<div class="row">
						<div class="col-lg-4">
						</div>
						<div class="col-lg-4 login-form-container">
							<form method="post" action="">
								<div class="row">
									<div class="col-lg-12">
										<div class="login-title">House of Hope Foundation Occupancy Status</div>
									</div>
								</div>
								<div class="row">
									<div class="col-lg-12 wrap-input">
										<div class="input"> {{ form.username }} </div>
										<span class="input-focus"></span>
										<span class="input-symbol">
											<i class="fa fa-user" aria-hidden="true"></i>
										</span>
									</div>
								</div>
								<div class="row">
									<div class="col-lg-12 wrap-input">
										<div class="input"> {{ form.password }} </div>
										<span class="input-focus"></span>
										<span class="input-symbol">
											<i class="fa fa-lock" aria-hidden="true"></i>
										</span>
									</div>
								</div>
								<div class="login-form-btn-container">
									<button class="login-form-btn">Login</button>
								</div>
							</form>
						</div>
						<div class="col-lg-4">
						</div>
					</div>
				</div>
			</div>
		</div>
    </body>
</html>